pipeline {
    agent any

    stages {
        stage ('Compile Stage') {

            steps {
                withMaven(maven : 'M3') {
                    sh 'mvn -f OutdoorBuddiesWeb/pom.xml clean compile'
                }
            }
        }


        stage ('Deployment Stage') {
            steps {
                withMaven(maven : 'M3') {
                    sh 'mvn -f OutdoorBuddiesWeb/pom.xml spring-boot:run'
                }
            }
        }
    }
}